config/routes.rb
Rails.application.routes.draw do
  resources :my_clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "my_clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/my_client.rb
class MyClient < ApplicationRecord
  has_one_attached :client_logo

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/my_clients_controller.rb
class MyClientsController < ApplicationController
  before_action :set_my_client, only: %i[ show edit update destroy ]

  # GET /my_clients or /my_clients.json
  def index
    @my_clients = MyClient.all
  end

  # GET /my_clients/1 or /my_clients/1.json
  def show
  end

  # GET /my_clients/new
  def new
    @my_client = MyClient.new
  end

  # GET /my_clients/1/edit
  def edit
  end

  # POST /my_clients or /my_clients.json
  def create
    @my_client = MyClient.new(my_client_params)

    respond_to do |format|
      if @my_client.save
        $redis.set(@my_client.slug, @my_client)
        format.html { redirect_to @my_client, notice: "My client was successfully created." }
        format.json { render :show, status: :created, location: @my_client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @my_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_clients/1 or /my_clients/1.json
  def update
    old_slug = @my_client.slug

    respond_to do |format|
      if @my_client.update(my_client_params)
        $redis.del(old_slug) if old_slug != @my_client.slug

        $redis.set(@my_client.slug, @my_client)

        format.html { redirect_to @my_client, notice: "My client was successfully updated." }
        format.json { render :show, status: :ok, location: @my_client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @my_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_clients/1 or /my_clients/1.json
  def destroy
    respond_to do |format|
      @my_client.update_attribute(:deleted_at, Time.current)
      $redis.del(@my_client.slug)

      format.html { redirect_to my_clients_path, status: :see_other, notice: "My client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_client
      @my_client = MyClient.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def my_client_params
      params.require(:my_client)
                             .permit(:name, :slug, :is_project, :self_capture, :client_prefix,
                                     :client_logo, :address, :phone_number, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_clients_helper.rb
module MyClientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsiAsiaPasificTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/my_clients/_form.html.erb
<%= form_with(model: my_client) do |form| %>
  <% if my_client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(my_client.errors.count, "error") %> prohibited this my_client from being saved:</h2>

      <ul>
        <% my_client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name, value: my_client.name, required: true %>
  </div>

  <div>
    <%= form.label :is_project %>
    <%= form.text_field :is_project, value: my_client.is_project, required: true %>
  </div>

  <div>
    <%= form.label :self_capture %>
    <%= form.text_field :self_capture, value: my_client.self_capture, required: true %>
  </div>

  <div>
    <%= form.label :client_prefix %>
    <%= form.text_field :client_prefix, value: my_client.client_prefix, required: true %>
  </div>

  <div>
    <%= form.label :client_logo %>
    <%= form.file_field :client_logo %>
  </div>

  <div>
    <%= form.label :phone_number %>
    <%= form.telephone_field :phone_number, value: my_client.phone_number, required: true %>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address, value: my_client.address, required: true %>
  </div>

  <div>
    <%= form.label :city %>
    <%= form.text_field :city, value: my_client.city, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/my_clients/_my_client.html.erb
<div id="<%= dom_id my_client %>">
  <div>
    <p>Name: <%= my_client.name %></p>
    <p>Slug: <%= my_client.slug %></p>
    <p>Is Project: <%= my_client.is_project %></p>
    <p>Self Capture: <%= my_client.self_capture %></p>
    <p>Client Prefix: <%= my_client.client_prefix %></p>
    <p>Client Logo: <%= image_tag my_client.client_logo, alt: "Clinet Logo", size: "100x100" if my_client.client_logo.attached? %></p>
    <p>Phone Number: <%= my_client.phone_number %></p>
    <p>Address: <%= my_client.address %></p>
    <p>city: <%= my_client.city %></p>
  </div>
</div>

app/views/my_clients/edit.html.erb
<h1>Editing my client</h1>

<%= render "form", my_client: @my_client %>

<br>

<div>
  <%= link_to "Show this my client", @my_client %> |
  <%= link_to "Back to my clients", my_clients_path %>
</div>

app/views/my_clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>My clients</h1>

<div id="my_clients">
  <% @my_clients.each do |my_client| %>
    <% if my_client.deleted_at.nil? || my_client.deleted_at.blank? %>
      <%= render my_client %>
      <p>
        <%= link_to "Show this my client", my_client %>
      </p>
      <hr>
    <% end %>
  <% end %>
</div>

<%= link_to "New my client", new_my_client_path %>

app/views/my_clients/new.html.erb
<h1>New my client</h1>

<%= render "form", my_client: @my_client %>

<br>

<div>
  <%= link_to "Back to my clients", my_clients_path %>
</div>

app/views/my_clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @my_client %>

<div>
  <%= link_to "Edit this my client", edit_my_client_path(@my_client) %> |
  <%= link_to "Back to my clients", my_clients_path %>

  <%= button_to "Destroy this my client", @my_client, method: :delete %>
</div>